In [1]:
import librosa
import librosa.display
import IPython.display as ipd
import matplotlib.pyplot as plt 
import numpy as np
from pathlib import Path
import random
import pandas as pd
from statistics import mean

In [2]:
data = pd.read_json('../4_accent_features_8k.json')

In [3]:
data

,lable,rms,zrc,sb,sc,mfcc
0,bangla,"[0.0013022722, 0.0017205017000000002, 0.001578...","[0.0712890625, 0.1396484375, 0.142578125, 0.13...","[795.9049247021, 844.9831554604, 890.971914505...","[801.0601386723, 851.0365678407, 978.604145012...","[[-443.1603393555, -422.7786865234, -423.59481..."
1,malayalam,"[0.0019007573, 0.0026969092, 0.0024940472, 0.0...","[0.0712890625, 0.1474609375, 0.1591796875, 0.1...","[751.0645191972, 761.4017819413, 771.918327785...","[782.1835638066, 861.6459650473, 854.403650816...","[[-428.3286437988, -393.4295654297, -394.17318..."
2,malayalam,"[0.0019902054000000002, 0.0023496253000000003,...","[0.06054687500000001, 0.138671875, 0.155273437...","[835.2683419914, 869.5909474385, 862.921266800...","[799.9404110335, 870.736104638, 901.550001952,...","[[-437.4763183594, -409.4303588867, -412.71850..."
3,odiya,"[0.0018824536, 0.0026095212, 0.002663172500000...","[0.06640625, 0.1396484375, 0.1376953125, 0.132...","[803.6664493043, 793.4924641575, 801.737168895...","[854.5985286383, 832.038648165, 830.6994559488...","[[-434.8092041016, -401.2186584473, -400.85339..."
4,bangla,"[0.00199213, 0.0028055811, 0.0028021345, 0.002...","[0.08984375, 0.17578125, 0.1552734375, 0.15429...","[853.9057514039, 815.3463371834, 875.239832466...","[971.5535952292, 916.9148191011, 966.702269077...","[[-399.463104248, -372.8232116699, -373.531829..."
...,...,...,...,...,...,...
6178,telugu,"[0.0014494726, 0.055635470900000004, 0.0765934...","[0.068359375, 0.1337890625, 0.099609375, 0.050...","[820.9125489137, 539.7206969134, 494.040615590...","[859.4978397385, 747.4675212448, 673.467429045...","[[-332.5925598145, -184.8822174072, -165.35314..."
6179,odiya,"[0.0021822276, 0.0029424643, 0.0027601738, 0.0...","[0.0791015625, 0.1455078125, 0.126953125, 0.14...","[875.3101201428, 802.6967022014, 788.821870706...","[958.2656348969, 846.3804996667, 836.464415526...","[[-411.5061035156, -379.0005493164, -384.05307..."
6180,malayalam,"[0.0018016612, 0.0022565140000000003, 0.002092...","[0.0390625, 0.091796875, 0.1083984375, 0.12402...","[840.8434179348, 874.0352141954, 849.199936017...","[854.2836269544, 847.1916806041, 860.230710413...","[[-448.7952880859, -421.9195251465, -422.11801..."
6181,bangla,"[0.0013226597000000001, 0.0016902991, 0.001800...","[0.0810546875, 0.169921875, 0.162109375, 0.155...","[799.3445132141, 838.1066019972, 842.924535838...","[876.3167666297, 949.672900248, 913.8801781294...","[[-453.154876709, -426.0098266602, -424.723693..."
6182,telugu,"[0.0409149118, 0.0628683642, 0.0755056962, 0.0...","[0.0205078125, 0.0634765625, 0.087890625, 0.08...","[474.52173136, 567.5125738632, 494.3092740647,...","[372.562701833, 718.0790401324, 555.1412601319...","[[-256.2119750977, -205.5053863525, -193.34898..."

In [4]:
def get_min_avg_max(column, data=data):
    row_data_min, row_data_avg, row_data_max = [], [], []
    for row in data[column]:
        row_data_min.append(min(row))
        row_data_avg.append(mean(row))
        row_data_max.append(max(row))
    
    data.drop(column, axis=1, inplace=True)
    data[f'min_{column}'] = row_data_min
    data[f'avg_{column}'] = row_data_avg
    data[f'max_{column}'] = row_data_max
    
    return row_data_min, row_data_avg, row_data_max

In [5]:
a,b,c = get_min_avg_max('rms')
a,b,c = get_min_avg_max('zrc')
a,b,c = get_min_avg_max('sb')
a,b,c = get_min_avg_max('sc')

In [6]:
data

,lable,mfcc,min_rms,avg_rms,max_rms,min_zrc,avg_zrc,max_zrc,min_sb,avg_sb,max_sb,min_sc,avg_sc,max_sc
0,bangla,"[[-443.1603393555, -422.7786865234, -423.59481...",0.001302,0.085629,0.274967,0.050781,0.176424,0.395508,387.438403,803.934163,1168.027720,463.566313,1003.997707,1942.338477
1,malayalam,"[[-428.3286437988, -393.4295654297, -394.17318...",0.001901,0.054131,0.191938,0.050781,0.134560,0.245117,378.685831,711.221839,1009.749549,435.996168,800.498312,1349.526164
2,malayalam,"[[-437.4763183594, -409.4303588867, -412.71850...",0.001958,0.019840,0.125847,0.047852,0.130952,0.367188,477.778595,797.687435,1198.976339,437.141068,844.235767,1682.045204
3,odiya,"[[-434.8092041016, -401.2186584473, -400.85339...",0.001882,0.015328,0.066335,0.046875,0.129330,0.250000,363.824719,755.377248,980.044779,401.064784,810.301636,1293.554625
4,bangla,"[[-399.463104248, -372.8232116699, -373.531829...",0.001992,0.054969,0.196143,0.062500,0.142479,0.388672,273.543067,741.103758,1300.716837,465.474304,858.034120,2026.514792
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6178,telugu,"[[-332.5925598145, -184.8822174072, -165.35314...",0.001449,0.049301,0.126867,0.041992,0.102352,0.268555,316.337024,661.713862,1150.784442,381.637938,686.748140,1597.983110
6179,odiya,"[[-411.5061035156, -379.0005493164, -384.05307...",0.001966,0.020496,0.082519,0.045898,0.139918,0.383789,417.888161,791.410364,1253.398421,423.111493,890.967987,1865.436616
6180,malayalam,"[[-448.7952880859, -421.9195251465, -422.11801...",0.001485,0.031932,0.126697,0.039062,0.150211,0.463867,374.246925,836.059971,1186.026940,454.293864,964.311985,2156.357695
6181,bangla,"[[-453.154876709, -426.0098266602, -424.723693...",0.001323,0.059751,0.194759,0.062500,0.164551,0.542969,384.930257,785.124942,1147.130713,381.207811,938.532349,2132.159282
6182,telugu,"[[-256.2119750977, -205.5053863525, -193.34898...",0.001805,0.051525,0.201199,0.020508,0.118567,0.177734,393.877356,685.654945,887.282158,372.562702,714.522768,1181.776474

In [7]:
features = data.drop(['lable', 'mfcc'], axis=1)
features

,min_rms,avg_rms,max_rms,min_zrc,avg_zrc,max_zrc,min_sb,avg_sb,max_sb,min_sc,avg_sc,max_sc
0,0.001302,0.085629,0.274967,0.050781,0.176424,0.395508,387.438403,803.934163,1168.027720,463.566313,1003.997707,1942.338477
1,0.001901,0.054131,0.191938,0.050781,0.134560,0.245117,378.685831,711.221839,1009.749549,435.996168,800.498312,1349.526164
2,0.001958,0.019840,0.125847,0.047852,0.130952,0.367188,477.778595,797.687435,1198.976339,437.141068,844.235767,1682.045204
3,0.001882,0.015328,0.066335,0.046875,0.129330,0.250000,363.824719,755.377248,980.044779,401.064784,810.301636,1293.554625
4,0.001992,0.054969,0.196143,0.062500,0.142479,0.388672,273.543067,741.103758,1300.716837,465.474304,858.034120,2026.514792
...,...,...,...,...,...,...,...,...,...,...,...,...
6178,0.001449,0.049301,0.126867,0.041992,0.102352,0.268555,316.337024,661.713862,1150.784442,381.637938,686.748140,1597.983110
6179,0.001966,0.020496,0.082519,0.045898,0.139918,0.383789,417.888161,791.410364,1253.398421,423.111493,890.967987,1865.436616
6180,0.001485,0.031932,0.126697,0.039062,0.150211,0.463867,374.246925,836.059971,1186.026940,454.293864,964.311985,2156.357695
6181,0.001323,0.059751,0.194759,0.062500,0.164551,0.542969,384.930257,785.124942,1147.130713,381.207811,938.532349,2132.159282
6182,0.001805,0.051525,0.201199,0.020508,0.118567,0.177734,393.877356,685.654945,887.282158,372.562702,714.522768,1181.776474

In [8]:
lables = np.array(data['lable'])

# One-hot encode the data using pandas get_dummies
lables = pd.get_dummies(lables)
# Display the first 5 rows of the last 12 columns
lables.iloc[:,5:].head(5)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [9]:
from sklearn.model_selection import train_test_split

train_features, test_features, train_labels, test_labels = train_test_split(features, lables, test_size = 0.25, random_state = 42)

In [10]:
# Import the model we are using
from sklearn.ensemble import RandomForestRegressor
# Instantiate model with 1000 decision trees
rf = RandomForestRegressor(n_estimators = 1000, random_state = 42)
# Train the model on training data
rf.fit(train_features, train_labels)

RandomForestRegressor(n_estimators=1000, random_state=42)

In [11]:
# Use the forest's predict method on the test data
predictions = rf.predict(test_features)
predictions = rf.predict(test_features)

# Calculate the absolute errors
errors = abs(predictions - test_labels)
# Print out the mean absolute error (mae)
print('Mean Absolute Error:\n', round(np.mean(errors), 2), 'degrees.')

Mean Absolute Error:
 bangla       0.09
malayalam    0.14
odiya        0.06
telugu       0.12
dtype: float64 degrees.

/home/rutvik/Projects/Final_Year_Project/venv/lib/python3.9/site-packages/numpy/core/fromnumeric.py:3430: FutureWarning: In a future version, DataFrame.mean(axis=None) will return a scalar mean over the entire DataFrame. To retain the old behavior, use 'frame.mean(axis=0)' or just 'frame.mean()'
  return mean(axis=axis, dtype=dtype, out=out, **kwargs)

In [12]:
errors

      bangla  malayalam  odiya  telugu
1426   0.010      0.002  0.000   0.008
2328   0.000      0.505  0.505   0.000
5713   0.076      0.007  0.000   0.069
2110   0.114      0.655  0.000   0.541
5069   0.189      0.051  0.001   0.241
...      ...        ...    ...     ...
5001   0.000      0.000  0.000   0.000
6076   0.259      0.134  0.000   0.125
3528   0.602      0.015  0.000   0.587
203    0.105      0.103  0.000   0.208
339    0.032      0.004  0.000   0.036

[1546 rows x 4 columns]

In [13]:
# Calculate mean absolute percentage error (MAPE)
mape = 100 * (errors)
# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:\n', round(accuracy, 2), '%.')

Accuracy:
 bangla       91.26
malayalam    85.78
odiya        94.35
telugu       87.95
dtype: float64 %.

/home/rutvik/Projects/Final_Year_Project/venv/lib/python3.9/site-packages/numpy/core/fromnumeric.py:3430: FutureWarning: In a future version, DataFrame.mean(axis=None) will return a scalar mean over the entire DataFrame. To retain the old behavior, use 'frame.mean(axis=0)' or just 'frame.mean()'
  return mean(axis=axis, dtype=dtype, out=out, **kwargs)