In [1]:
import librosa
import librosa.display
import IPython.display as ipd
import matplotlib.pyplot as plt 
import numpy as np
from pathlib import Path
import random
import pandas as pd
from statistics import mean

In [2]:
data = pd.read_json('../5_accent_features_8k.json')

In [3]:
data

,lable,rms,zrc,sb,sc,mfcc
0,american,"[0.10995900630000001, 0.123431541, 0.057550724...","[0.1611328125, 0.2001953125, 0.2119140625, 0.3...","[982.3833614816, 998.6809827277, 1227.21971388...","[1026.7194059383, 921.3751421883, 1687.1791594...","[[-132.202331543, -106.4561920166, -144.163803..."
1,american,"[0.0449587628, 0.0892027393, 0.0972395092, 0.1...","[0.208984375, 0.310546875, 0.1513671875, 0.100...","[963.9106217367, 897.3924172554, 900.666981819...","[1576.1782294645, 1341.2154906595, 1251.823100...","[[-120.1662216187, -64.2591247559, -84.6273498..."
2,american,"[0.0351665355, 0.10262352970000001, 0.10095142...","[0.078125, 0.12109375, 0.064453125, 0.07128906...","[923.2569985211, 954.1517268996, 936.182168068...","[729.6191839967, 906.2135315307, 772.504023950...","[[-204.3710479736, -111.2505950928, -130.19665..."
3,indian,"[0.058094892700000005, 0.0720619857, 0.0426379...","[0.1396484375, 0.171875, 0.0625, 0.0673828125,...","[1126.3458385918, 1075.1604486286, 916.9369396...","[1119.0037267103, 1001.3589439764, 686.3549935...","[[-204.9865570068, -181.3363800049, -285.47653..."
4,american,"[0.0127645116, 0.055047065000000006, 0.0553400...","[0.1171875, 0.158203125, 0.0517578125, 0.04492...","[945.6208621592, 965.5379844122, 939.509883464...","[576.6528108766, 952.5287575697, 825.655844384...","[[-238.695098877, -131.825668335, -140.2941741..."
...,...,...,...,...,...,...
11125,indian,"[0.005203237800000001, 0.0583481714, 0.0883544...","[0.1484375, 0.1748046875, 0.0546875, 0.0595703...","[939.0655020602, 735.4849804102, 842.864382448...","[1085.5789562353, 633.6020721972, 746.87798516...","[[-392.308380127, -253.5061950684, -204.861923..."
11126,british,"[0.0670182556, 0.11963738500000001, 0.13444279...","[0.0966796875, 0.140625, 0.072265625, 0.056640...","[279.7990742638, 691.1704207535, 1057.99920323...","[334.4932575184, 602.9638842564, 910.891398897...","[[-296.3085021973, -209.2213897705, -214.50019..."
11127,australian,"[0.0458770357, 0.06701447070000001, 0.05166622...","[0.0791015625, 0.11328125, 0.2255859375, 0.267...","[889.8696890516, 1050.0291055209, 1192.2407333...","[831.469767543, 1120.86074567, 963.4700761504,...","[[-158.1745147705, -105.2735824585, -136.48347..."
11128,american,"[0.1035422683, 0.1399547011, 0.0942250416, 0.0...","[0.11523437500000001, 0.1923828125, 0.23339843...","[578.4063870442, 687.3923714443, 871.801319026...","[740.7449395003, 995.2480438369, 1025.91691399...","[[-106.186164856, -56.3407363892, -119.2368698..."
11129,indian,"[0.0143631678, 0.0487043858, 0.0869188607, 0.1...","[0.12890625, 0.1630859375, 0.0751953125, 0.066...","[612.8867126285, 632.5646167517, 743.737460231...","[406.2776748625, 455.8883271732, 818.600459216...","[[-472.9836425781, -234.4741210938, -170.09353..."

In [4]:
def get_min_avg_max(column, data=data):
    row_data_min, row_data_avg, row_data_max = [], [], []
    for row in data[column]:
        row_data_min.append(min(row))
        row_data_avg.append(mean(row))
        row_data_max.append(max(row))
    
    data.drop(column, axis=1, inplace=True)
    data[f'min_{column}'] = row_data_min
    data[f'avg_{column}'] = row_data_avg
    data[f'max_{column}'] = row_data_max
    
    return row_data_min, row_data_avg, row_data_max

In [5]:
a,b,c = get_min_avg_max('rms')
a,b,c = get_min_avg_max('zrc')
a,b,c = get_min_avg_max('sb')
a,b,c = get_min_avg_max('sc')

In [6]:
data

,lable,mfcc,min_rms,avg_rms,max_rms,min_zrc,avg_zrc,max_zrc,min_sb,avg_sb,max_sb,min_sc,avg_sc,max_sc
0,american,"[[-132.202331543, -106.4561920166, -144.163803...",0.001167,0.103407,0.189941,0.067383,0.189209,0.440430,394.431290,880.691752,1307.266225,434.735910,1009.641142,2161.378419
1,american,"[[-120.1662216187, -64.2591247559, -84.6273498...",0.000801,0.058658,0.103927,0.079102,0.212576,0.539062,480.439854,870.267340,1122.283493,422.148634,1097.386582,2123.551926
2,american,"[[-204.3710479736, -111.2505950928, -130.19665...",0.000754,0.067203,0.109837,0.047852,0.204605,0.706055,448.441120,828.700336,1435.614128,291.909819,991.248812,2980.423978
3,indian,"[[-204.9865570068, -181.3363800049, -285.47653...",0.001090,0.056282,0.122838,0.056641,0.161513,0.534180,436.448730,899.991063,1271.609599,369.349090,1044.968954,2045.723166
4,american,"[[-238.695098877, -131.825668335, -140.2941741...",0.005269,0.055942,0.114724,0.044922,0.132704,0.386719,547.596459,1014.481168,1391.435266,395.814580,1026.078903,2352.828746
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11125,indian,"[[-392.308380127, -253.5061950684, -204.861923...",0.000496,0.051814,0.105858,0.054688,0.196100,0.597656,407.614581,888.767232,1286.562931,327.117005,1075.957907,2119.978221
11126,british,"[[-296.3085021973, -209.2213897705, -214.50019...",0.010991,0.076711,0.134443,0.046875,0.142241,0.453125,279.799074,837.773872,1161.597266,334.493258,889.486936,2626.316454
11127,australian,"[[-158.1745147705, -105.2735824585, -136.48347...",0.006336,0.063076,0.114340,0.035156,0.144206,0.616211,715.505224,988.036607,1311.033228,566.711898,1066.883145,2340.979582
11128,american,"[[-106.186164856, -56.3407363892, -119.2368698...",0.005160,0.094933,0.188103,0.073242,0.219238,0.410156,471.818934,809.624811,1178.005456,651.189324,1095.364001,1907.227408
11129,indian,"[[-472.9836425781, -234.4741210938, -170.09353...",0.000523,0.062909,0.127007,0.060547,0.182408,0.486328,465.102776,819.474318,1156.474441,406.277675,1022.974252,2009.081023

In [7]:
features = data.drop(['lable', 'mfcc'], axis=1)
features

,min_rms,avg_rms,max_rms,min_zrc,avg_zrc,max_zrc,min_sb,avg_sb,max_sb,min_sc,avg_sc,max_sc
0,0.001167,0.103407,0.189941,0.067383,0.189209,0.440430,394.431290,880.691752,1307.266225,434.735910,1009.641142,2161.378419
1,0.000801,0.058658,0.103927,0.079102,0.212576,0.539062,480.439854,870.267340,1122.283493,422.148634,1097.386582,2123.551926
2,0.000754,0.067203,0.109837,0.047852,0.204605,0.706055,448.441120,828.700336,1435.614128,291.909819,991.248812,2980.423978
3,0.001090,0.056282,0.122838,0.056641,0.161513,0.534180,436.448730,899.991063,1271.609599,369.349090,1044.968954,2045.723166
4,0.005269,0.055942,0.114724,0.044922,0.132704,0.386719,547.596459,1014.481168,1391.435266,395.814580,1026.078903,2352.828746
...,...,...,...,...,...,...,...,...,...,...,...,...
11125,0.000496,0.051814,0.105858,0.054688,0.196100,0.597656,407.614581,888.767232,1286.562931,327.117005,1075.957907,2119.978221
11126,0.010991,0.076711,0.134443,0.046875,0.142241,0.453125,279.799074,837.773872,1161.597266,334.493258,889.486936,2626.316454
11127,0.006336,0.063076,0.114340,0.035156,0.144206,0.616211,715.505224,988.036607,1311.033228,566.711898,1066.883145,2340.979582
11128,0.005160,0.094933,0.188103,0.073242,0.219238,0.410156,471.818934,809.624811,1178.005456,651.189324,1095.364001,1907.227408
11129,0.000523,0.062909,0.127007,0.060547,0.182408,0.486328,465.102776,819.474318,1156.474441,406.277675,1022.974252,2009.081023

In [8]:
lables = np.array(data['lable'])

# One-hot encode the data using pandas get_dummies
lables = pd.get_dummies(lables)
# Display the first 5 rows of the last 12 columns
lables.iloc[:,5:].head(5)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [9]:
from sklearn.model_selection import train_test_split

train_features, test_features, train_labels, test_labels = train_test_split(features, lables, test_size = 0.25, random_state = 42)

In [10]:
# Import the model we are using
from sklearn.ensemble import RandomForestRegressor
# Instantiate model with 1000 decision trees
rf = RandomForestRegressor(n_estimators = 1000, random_state = 42)
# Train the model on training data
rf.fit(train_features, train_labels)

RandomForestRegressor(n_estimators=1000, random_state=42)

In [11]:
# Use the forest's predict method on the test data
predictions = rf.predict(test_features)

# Calculate the absolute errors
errors = abs(predictions - test_labels)
# Print out the mean absolute error (mae)
print('Mean Absolute Error:\n', round(np.mean(errors), 2), 'degrees.')

Mean Absolute Error:
 american      0.34
australian    0.11
british       0.16
indian        0.17
welsh         0.11
dtype: float64 degrees.

/home/rutvik/Projects/Final_Year_Project/venv/lib/python3.9/site-packages/numpy/core/fromnumeric.py:3430: FutureWarning: In a future version, DataFrame.mean(axis=None) will return a scalar mean over the entire DataFrame. To retain the old behavior, use 'frame.mean(axis=0)' or just 'frame.mean()'
  return mean(axis=axis, dtype=dtype, out=out, **kwargs)

In [12]:
errors

      american  australian  british  indian  welsh
6113     0.780       0.037    0.008   0.885  0.060
483      0.498       0.018    0.286   0.084  0.110
8406     0.612       0.092    0.836   0.067  0.065
7238     0.649       0.731    0.018   0.016  0.048
5627     0.432       0.068    0.036   0.041  0.287
...        ...         ...      ...     ...    ...
5135     0.461       0.014    0.013   0.236  0.724
8856     0.165       0.002    0.306   0.125  0.014
7798     0.460       0.260    0.775   0.020  0.035
2826     0.092       0.012    0.010   0.061  0.009
2724     0.448       0.003    0.112   0.082  0.251

[2783 rows x 5 columns]

In [13]:
# Calculate mean absolute percentage error (MAPE)
mape = 100 * (errors)
# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:\n', round(accuracy, 2), '%.')

Accuracy:
 american      65.56
australian    88.58
british       83.78
indian        83.29
welsh         89.30
dtype: float64 %.

/home/rutvik/Projects/Final_Year_Project/venv/lib/python3.9/site-packages/numpy/core/fromnumeric.py:3430: FutureWarning: In a future version, DataFrame.mean(axis=None) will return a scalar mean over the entire DataFrame. To retain the old behavior, use 'frame.mean(axis=0)' or just 'frame.mean()'
  return mean(axis=axis, dtype=dtype, out=out, **kwargs)

In [23]:
pred = np.round(rf.predict(test_features))
pred

array([[1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       ...,
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.]])

In [29]:
def one_hot_to_lbl(lbl, pred):
    lbl_outpt = []
    pred_outpt = []
    lst = ["american", "australian", "british", "indian", "welsh"]
    print(lbl, pred)
    for i in range(len(lbl)):
        if np.sum(pred[i]):
            lbl_outpt.append(lst[np.where(pred[i] == 1)[0][0]])
            pred_outpt.append(lst[np.where(lbl[i] == 1)[0][0]])        
    return np.array(lbl_outpt), np.array(pred_outpt)

new_test_lables, predictions = one_hot_to_lbl(test_labels, pred)

      american  australian  british  indian  welsh
6113         0           0        0       1      0
483          1           0        0       0      0
8406         0           0        1       0      0
7238         0           1        0       0      0
5627         1           0        0       0      0
...        ...         ...      ...     ...    ...
5135         0           0        0       0      1
8856         0           0        1       0      0
7798         0           0        1       0      0
2826         1           0        0       0      0
2724         1           0        0       0      0

[2783 rows x 5 columns] [[1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]

KeyError: 0

In [19]:
from sklearn.metrics import classification_report
print(classification_report(test_labels,rf.predict(test_features)))

ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets